apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- files:
  - tls.key
  - tls.crt
  name: signer-ca
  namespace: signer-ca-system
  type: kubernetes.io/tls
resources:
- rbac.yaml
- ../default
patchesStrategicMerge:
- patch_add_signer_pki_files.yaml
images:
- name: controller
  newName: gcr.io/ignasi-permanent-ffxxqcd8/cert-manager/signer-ca-controller
  newTag: d560ca1-dirty
